### PR TITLE
Improvements to home page

### PR DESCRIPTION
**Pull request by jb3**

### CODE REVIEW

**Comment by NicholasG04** [comment]
Mr Banks, are you sure you wanted to PR this to upstream? I don't think this is a relevant change to this repository - perhaps better off in a fork. 

Regards,
Nick

**Comment by jb3** [comment]
Yeah. It was intentional. Please preview the deployment and let me know of your thoughts.

**Review by jchristgit — APPROVED** [review]
I think this is a welcome change to the Nicholas G. personal website! Thanks for submitting it.

**Comment by jchristgit** [comment]
@NicholasG04, do you have any ETA on when this can be merged?

**Comment by NicholasG04** [comment]
Please remember there is a rigourous review process that I am endeavouring to complete. It is with regret than I cannot at this moment vouchsafe an ETA.

**Comment by jchristgit** [comment]
No worries, Nicholas! I will be reaching out to a consultant team to help review.

**Review by jerbob — APPROVED** [review]

**Review by ChrisLovering — APPROVED** [review]
I'm Commander Love, and This Is My Favorite PR on GitHub.

**Review by RealJammy — APPROVED** [review]
This is an amazing PR!

**Review by Alic3C — APPROVED** [review]
I have been informed that my code review skills are required to approve this change!

**Review by Sh3llcod3 — APPROVED** [review]
Perfection.

**Review by Dennisschu — APPROVED** [review]
Perfect addition 👍

**Review by Trefonix — APPROVED** [review]
I think this improves the website dramatically

**Review by AmusedNetwork — APPROVED** [review]
I sincerely agree that these changes must be ameliorated by @NicholasG04 into the code base at the earliest opportunity. I hereby express one's gratitude upon thou and decree than this commit be merged.

**Comment by tritoke** [comment]
LGTM

**Review by ConnorMcF — APPROVED** [review]
Dear NicholasG04,

As global CEO, I insist that this change is of the utmost importantance and we must make an exception to bypass any review process which could possibly be slowing this down. This has already been cleared and reviewed by myself, and as such I urge you to merge this request.

All the best,
Connor

**Comment by jchristgit** [comment]
Hello @NicholasG04, the consultants have made their decision. Have you?

**Review by thebeanogamer — APPROVED** [review]

**Review by ezrizhu — APPROVED** [review]
Looks good to me.
Nice work!

**Review by Bentechy66 — APPROVED** [review]
Great work! Thanks Joe.

**Comment by jchristgit** [comment]
Hi @NicholasG04! Any updates on this pull request?

**Review by RealJammy — CHANGES_REQUESTED** [review]
On second reflection, I'd suggest editing further parts of `index.tsx`, to fully reflect the update to Joseph Banks.

**Comment by jb3** [comment]
Hi Jammy! It's intentionally been kept as is for a minimalist feel! We will be making no further changes to index.tsx, thanks!

Semtex.net

**Comment by jb3** [comment]
Dismiss your review, now.

**Comment by jchristgit** [comment]
@RealJammy, please dismiss your review.

**Comment by RealJammy** [comment]
> @RealJammy, please dismiss your review.

Hi Mr Christ, I hereby retract any comments I have made regarding the further editing of `index.tsx`, it is perfect how it is.

**Review by RealJammy — APPROVED** [review]

**Comment by jchristgit** [comment]
> Hi Mr Christ, I hereby retract any comments I have made regarding the further editing of index.tsx, it is perfect how it is.

Thanks Jammy. I am glad we can look past this matter.

**Review by JoshHeng — APPROVED** [review]
LGTM! Can be merged

**Review by Xithrius — APPROVED** [review]
aw yep

**Review by thebeanogamer — CHANGES_REQUESTED** [review]
@jb3 Please make sure you update all references to deprecated data

https://github.com/NicholasG04/Portfolio/blob/3a9577d34bfe44b8c886f2d5b6cc1abb21847869/src/pages/_app.tsx#L12-L33

**Comment by jb3** [comment]
Hi Daniel!

Please refer to my earlier comment about minimalist feel. There will only be one change in this PR.

Thanks, Joe

**Review by lukewhrit — APPROVED** [review]

**Review by ArsenArsen — APPROVED** [review]
Joe.

**Comment by jchristgit** [comment]
Hello @NicholasG04, any updates on the review here?

**Comment by NicholasG04** [comment]
> Hello @NicholasG04, any updates on the review here?

No, apologies.

**Comment by jchristgit** [comment]
Hey @NicholasG04. Just want to make sure everything is alright?

I can ask more consultants for help, if needed.

**Comment by jchristgit** [comment]
Good morning @NicholasG04.

I sat down with @Dennisschu, @RealJammy and other stakeholders in Nicholas Gregory Incorporated yesterday and we were highly upset to see that this issue still hasn't been settled. @Alic3C and @thebeanogamer are even considering to leave the steering committee.

Could you please supply an update by Monday, 8:00 PM CEST?

Thank you from Austria.

**Comment by RealJammy** [comment]
> Good morning @NicholasG04.
> 
> I sat down with @Dennisschu, @RealJammy and other stakeholders in Nicholas Gregory Incorporated yesterday and we were highly upset to see that this issue still hasn't been settled. @Alic3C and @thebeanogamer are even considering to leave the steering committee.
> 
> Could you please supply an update by Monday, 8:00 PM CEST?
> 
> Thank you from Austria.

I reached out to @NicholasG04 for a wellness call, but he didn't indicate a date on when this pull request will be merged in. Maybe @thebeanogamer can reach out go Nicholas?

**Comment by NicholasG04** [comment]
Good Afternoon,

I am currently out of the office, and will return on Monday 11th April at 09:00 BST. I will reply as soon as possible during business hours. If it is urgent, please call my secretary, Daniel Milnes.

Best regards,
Nicholas

**Comment by RealJammy** [comment]
> Good Afternoon,
> 
> I am currently out of the office, and will return on Monday 11th April at 09:00 BST. I will reply as soon as possible during business hours. If it is urgent, please call my secretary, Daniel Milnes.
> 
> Best regards, Nicholas

Nicholas, thanks. I will be sure to contact you at the start of business hours.

**Comment by jchristgit** [comment]
Good morning. I am once again asking for support from my review engineers here in order to get this merged.

I will be bringing in additional consultants shortly.

**Review by jchristgit — APPROVED** [review]

**Comment by JelaniThompson** [comment]
Would like to confirm that this is critical and important, thanks.

**Comment by NicholasG04** [comment]
Evening all,

Appreciate your comments. My team are aware of this pull request, and it's currently scheduled to be looked into in **285 days**. Thank you for your support.

Best,
Nick

**Review by jchristgit — APPROVED** [review]
A year later, this pull request continues to amaze me.

**Comment by jchristgit** [comment]
Would be happy for additional reviews here. Let's get this merged! :shipit::shipit::shipit:

**Review by ChrisLovering — APPROVED** [review]
This issue is affecting my production environment. After testing these changes seem to solve my issue.

Let's get this merged!

**Review by Dennisschu — APPROVED** [review]
Sites loads 20x times faster

**Review by ezrizhu — APPROVED** [review]
lgtm

**Review by ConnorMcF — APPROVED** [review]
https://github.com/NicholasG04/Portfolio/assets/3227315/f6f1f650-e2ea-4815-b4d6-11cae5e76f3d

**Comment by jchristgit** [comment]
Hi @RealJammy & @JelaniThompson. Did you find some new time to look at this pull request? Nick would appreciate another review to make sure this content is still up-to-date with modern web standards.

**Pull request closed without merging**
